// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/auth-screens/ForgotPassword.tsx": () => import("../components/mockups/auth-screens/ForgotPassword.tsx"),
  "./components/mockups/auth-screens/Login.tsx": () => import("../components/mockups/auth-screens/Login.tsx"),
  "./components/mockups/auth-screens/Signup.tsx": () => import("../components/mockups/auth-screens/Signup.tsx")
};
